homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret lat
  longitude: !secret long
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: !secret elev
  # metric for Metric, imperial for Imperial
  unit_system: imperial
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: !secret tz
  # Customization file
  customize: !include customize.yaml

# Show links to resources in log and frontend
#introduction:

# Enables the frontend
frontend:

# Enables configuration UI
config:

http:
  # Secrets are defined in the file secrets.yaml
  api_password: !secret http_password
  # Uncomment this if you are using SSL/TLS, running in Docker container, etc.
  # base_url: example.duckdns.org:8123

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

# Enables a map showing the location of tracked devices
map:

# Track the sun
sun:

# Text to speech
tts:
  - platform: google

# Cloud
cloud:

# Insteon
insteon_local:
  host: !secret insteon_ip
  username: !secret insteon_u
  password: !secret insteon_p

# Arlo
arlo:
  username: !secret arlo_u
  password: !secret arlo_p

camera:
  - platform: arlo
  - platform: generic
    still_image_url: https://forecast.weather.gov/meteograms/Plotter.php?lat=39.9292&lon=-105.155&wfo=BOU&zcode=COZ039&gset=15&gdiff=3&unit=0&tinfo=MY7&ahour=0&pcmd=11011111111110000000000000000000000000000000000000000000000&lg=en&indu=1!1!1!&dd=&bw=&hrspan=48&pqpfhr=6&psnwhr=6
    name: Hourly Weather Forecast Graph
  - platform: generic
    still_image_url: http://www.goes.noaa.gov/GIFS/WCI8.JPG
    name: Western USA


#alarm_control_panel:
#  - platform: arlo

# Nest
nest:
  client_id: !secret nest_id
  client_secret: !secret nest_secret

# Rachio
switch:
  - platform: rachio
    access_token: !secret rachio_token
    manual_run_mins: 5

panel_iframe:
  rachio:
    title: Rachio
    url: https://app.rach.io
    icon: mdi:water-pump
  windy:
    title: Windy
    icon: mdi:weather-windy
    url: !secret windy_url
  wundermap:
    title: Wundermap
    icon: mdi:weather-sunny
    url: !secret wundermap_url
  mdiindex:
    title: MDI Icon Index
    icon: mdi:vector-square
    url: https://cdn.rawgit.com/james-fry/home-assistant-mdi/efd95d7a/home-assistant-mdi.html

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
sensor: !include sensors.yaml
zone: !include zones.yaml
