- platform: arlo
  monitored_conditions:
    - captured_today
    - last_capture
    - total_cameras
    - battery_level
    - signal_strength

# Weather prediction
- platform: wunderground
  api_key: !secret wunder_key
  monitored_conditions:
    - alerts
    - weather_1h
    - weather_2h
    - weather_3h
    - weather_4h
    - weather_5h
    - weather_6h
    - weather_7h
    - weather_8h
    - weather_1d
    - weather_1n
    - weather_2d
    - weather_2n
    - weather_3d
    - weather_3n

############################################################
##  Sensor Config for DSL Speed Test every 3 Hours        ##
############################################################

- platform: speedtest
  minute: 30
  hour:
    - 1
    - 3
    - 6
    - 9
    - 12
    - 15
    - 18
    - 21
  monitored_conditions:
    - ping
    - download
    - upload

############################################################
##     Sensor Config for Travel Time To / From Work       ##
############################################################

- platform: google_travel_time
  name: To Work (car)
  api_key: !secret gmaps_key
  origin: zone.home
  destination: zone.work
  options:
    units: imperial
    mode: driving

- platform: google_travel_time
  name: To Work (bicycle)
  api_key: !secret gmaps_key
  origin: zone.home
  destination: zone.work
  options:
    units: imperial
    mode: bicycling

- platform: google_travel_time
  name: To Home (car)
  api_key: !secret gmaps_key
  origin: zone.work
  destination: zone.home
  options:
    units: imperial
    mode: driving

- platform: google_travel_time
  name: To Home (bicycle)
  api_key: !secret gmaps_key
  origin: zone.work
  destination: zone.home
  options:
    units: imperial
    mode: bicycling
  
############################################################
##     Sensor Config for Home Assistant Version           ##
############################################################

- platform: version

############################################################
##       Sensor Config for Evenironmental Seasons         ##
############################################################

- platform: season
  type: astronomical

############################################################
##    Sensor Config for Next Sunrise Time Reformatting    ##
############################################################

- platform: template
  sensors: 
    nextsunrise:
      friendly_name: "Next Sun Rise"
      value_template: "{{ as_timestamp(states.sun.sun.attributes.next_rising) | timestamp_custom('%-H:%M') }}"
      icon_template: mdi:weather-sunset-up

    nextsunset:
      friendly_name: "Next Sun Set"
      value_template: "{{ as_timestamp(states.sun.sun.attributes.next_setting) | timestamp_custom('%-H:%M') }}"
      icon_template: mdi:weather-sunset-down

    solar_angle:
      friendly_name: Sun Angle
      unit_of_measurement: °
      value_template: >-
        {{ '%+.1f' | format(states.sun.sun.attributes.elevation) }}

    temp_1h:
      friendly_name: 1 hr
      unit_of_measurement: °F
      value_template: >-
        {{ float(states.sensor.pws_weather_1h.attributes.temp_f) | round(0) }}

    temp_2h:
      friendly_name: '2 hr'
      unit_of_measurement: "°F"
      value_template: >-
        {{ float(states.sensor.pws_weather_2h.attributes.temp_f) | round(0) }}
    
    temp_3h:
      friendly_name: '3 hr'
      unit_of_measurement: "°F"
      value_template: >-
        {{ float(states.sensor.pws_weather_3h.attributes.temp_f) | round(0) }}
    
    temp_4h:
      friendly_name: '4 hr'
      unit_of_measurement: "°F"
      value_template: >-
        {{ float(states.sensor.pws_weather_4h.attributes.temp_f) | round(0) }}

    temp_5h:
      friendly_name: '5 hr'
      unit_of_measurement: "°F"
      value_template: >-
        {{ float(states.sensor.pws_weather_5h.attributes.temp_f) | round(0) }}

    temp_6h:
      friendly_name: '6 hr'
      unit_of_measurement: "°F"
      value_template: >-
        {{ float(states.sensor.pws_weather_6h.attributes.temp_f) | round(0) }}

    temp_7h:
      friendly_name: '7 hr'
      unit_of_measurement: "°F"
      value_template: >-
        {{ float(states.sensor.pws_weather_7h.attributes.temp_f) | round(0) }}

    temp_8h:
      friendly_name: '8 hr'
      unit_of_measurement: "°F"
      value_template: >-
        {{ float(states.sensor.pws_weather_8h.attributes.temp_f) | round(0) }}

############################################################
##         Sensor Config for Home Assistant Uptime        ##
############################################################

- platform: uptime

############################################################
##     Sensor Config for Home Assistant Server Health     ##
############################################################
  
- platform: systemmonitor
  resources:
    - type: disk_use_percent
      arg: /
    - type: disk_free
      arg: /
    - type: memory_free
    - type: load_1m
    - type: load_5m
    - type: load_15m
    - type: processor_use
    - type: last_boot
    - type: since_last_boot
    - type: memory_use_percent

############################################################
##   Sensor Config for Home Assistant Server CPU Speed    ##
############################################################      

- platform: cpuspeed

############################################################
##        Travis CI for monitoring build state            ##
############################################################

- platform: travisci
  api_key: !secret github_token
  repository:
    - homeassistantconfig
  branch:
    - master
  monitored_conditions:
    - last_build_state
